# This file is automatically generated via sphinx-me
from sphinx_me import setup_conf; setup_conf(globals())
# These settings are added by Ian Welch to support SNM941 docs
import sphinx_bootstrap_theme
html_theme = 'bootstrap'
html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()
html_theme_options = {'bootswatch_theme': 'yeti', }
